name: Test PHP (0~5)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  level0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test lvl 0
        run: vendor/bin/phpstan analyse src --level 0
   
  level1:
    runs-on: ubuntu-latest
    needs: level0
    steps:
      - uses: actions/checkout@v3
      - name: Run test lvl 1
        run: vendor/bin/phpstan analyse src --level 1

  level2:
    runs-on: ubuntu-latest
    needs: level1
    steps:
      - uses: actions/checkout@v3
      - name: Run test lvl 2
        run: vendor/bin/phpstan analyse src --level 2

  level3:
    runs-on: ubuntu-latest
    needs: level2
    steps:
      - uses: actions/checkout@v3
      - name: Run test lvl 3
        run: vendor/bin/phpstan analyse src --level 3

  level4:
    runs-on: ubuntu-latest
    needs: level3
    steps:
      - uses: actions/checkout@v3
      - name: Run test lvl 4
        run: vendor/bin/phpstan analyse src --level 4

  level5:
    runs-on: ubuntu-latest
    needs: level4
    steps:
      - uses: actions/checkout@v3
      - name: Run test lvl 5
        run: vendor/bin/phpstan analyse src --level 5